# Generated by Django 2.2.7 on 2019-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
